THEME_NAME: gatsby-starter-blog
THEME_VERSION: 1.0.2

colors:
  light:
    primary: "#005b99"
    text: "#2e353f"
    text_light: "#4f5969"
    heading: "#1a202c"
    heading_black: "#000"
    accent: "#d1dce5"
    background: "#fff"
  dark:
    primary: "#fff"
    text: "#fff"
    text_light: "#fff"
    heading: "#fff"
    heading_black: "#fff"
    accent: "#fff"
    background: "#282C35"

font:
  family_sans: 'Montserrat, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'
  family_serif: '"Merriweather", "Georgia", Cambria, "Times New Roman", Times, serif'
  size: 16
