THEME_NAME: PaperMod
THEME_VERSION: 0.1.0
POSTS_PER_PAGINATION: 10

colors: 
  light: 
    theme: rgb(255, 255, 255)
    entry: rgb(255, 255, 255)
    primary: rgb(30, 30, 30)
    secondary: rgb(108, 108, 108)
    tertiary: rgb(214, 214, 214)
    content: rgb(31, 31, 31)
    hljs_bg: rgb(28, 29, 33)
    code_bg: rgb(245, 245, 245)
    border: rgb(238, 238, 238)
  dark: 
    theme: rgb(29, 30, 32)
    entry: rgb(46, 46, 51)
    primary: rgb(218, 218, 219)
    secondary: rgb(155, 156, 157)
    tertiary: rgb(65, 66, 68)
    content: rgb(196, 196, 197)
    hljs_bg: rgb(46, 46, 51)
    code_bg: rgb(55, 56, 62)
    border: rgb(51, 51, 51)

gap: 
  gap: 24px
  content_gap: 20px

height_width: 
  nav_width: 1024px
  main_width: 720px
  header_height: 60px
  footer_height: 60px

box: 
  radius: 8px

font: 
  family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Open Sans, Helvetica Neue, sans-serif
  size: 18px

settings:
  loop:
    authors: true
  post:
    authors: true
    tags: true
  footer:
    feed_icon: true